<?php

namespace AppBundle\Repository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    const FERESTRE_SIMPLE = 1;
    const FERESTRE_DUBLE = 2;
    const USI_DE_BALCON = 3;
    const USI_DE_INTERIOR = 4;
    const GLAFURI = 5;
    const PORTI_DE_GARAJ = 6;
    const TEHNICA_PARASOLARA = 7;

    public function getFerestreSimple()
    {
        $qb = $this->createQueryBuilder('c');
        $qb->andWhere('c.tip = :type')
            ->setParameter('type', self::FERESTRE_SIMPLE);
        $query = $qb->getQuery();
        return $query->getResult();
    }
}
