<?php

namespace AppBundle\Repository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    const FERESTRE_SIMPLE = 1;
    const FERESTRE_DUBLE = 2;
    const USI_DE_BALCON = 3;
    const USI_DE_INTERIOR = 4;
    const GLAFURI = 5;
    const PORTI_DE_GARAJ = 6;
    const TEHNICA_PARASOLARA = 7;

    public function getFerestreSimple()
    {
        return $this->getProductsOfType(self::FERESTRE_SIMPLE);
    }

    public function getFerestreDuble()
    {
        return $this->getProductsOfType(self::FERESTRE_DUBLE);
    }

    public function getUsiBalcon()
    {
        return $this->getProductsOfType(self::USI_DE_BALCON);
    }

    public function getUsiInterior()
    {
        return $this->getProductsOfType(self::USI_DE_INTERIOR);
    }

    public function getGlafuri()
    {
        return $this->getProductsOfType(self::GLAFURI);
    }

    public function getPortiGaraj()
    {
        return $this->getProductsOfType(self::PORTI_DE_GARAJ);
    }

    public function getTehnicaParasolara()
    {
        return $this->getProductsOfType(self::TEHNICA_PARASOLARA);
    }

    public function getProductsOfType($type)
    {
        $qb = $this->createQueryBuilder('c');
        $qb->andWhere('c.tip = :type')
            ->setParameter('type', $type);
        $query = $qb->getQuery();
        return $query->getResult();
    }
}
