app:
    resource: '@AppBundle/Controller/'
    type: annotation

logout:
    path:   /logout

tamplarie_pvc:
  path: /tamplarie_pvc
  defaults: { _controller: AppBundle:Product:tamplariepvc }

cerere_oferta:
  path: /cerere_oferta
  defaults: { _controller: AppBundle:Oferta:cerere }

cerere_oferta_success:
  path: /cerere_oferta_success
  defaults: { _controller: AppBundle:Oferta:success }

ferestre_simple:
  path: /ferestre_simple
  defaults: { _controller: AppBundle:Product:ferestreSimple }

ferestre_duble:
  path: /ferestre_duble
  defaults: { _controller: AppBundle:Product:ferestreDuble }

usi_balcon:
  path: /usi_balcon
  defaults: { _controller: AppBundle:Product:usiBalcon }

usi_interior:
  path: /usi_interior
  defaults: { _controller: AppBundle:Product:usiInterior }

glafuri:
  path: /glafuri
  defaults: { _controller: AppBundle:Product:glafuri }

porti_garaj:
  path: /porti_garaj
  defaults: { _controller: AppBundle:Product:portiGaraj }

tehnica_parasolara:
  path: /tehnica_parasolara
  defaults: { _controller: AppBundle:Product:tehnicaParasolara }

shopping_cart_add:
  path: /shopping_cart_add/{id}
  requirements:
    id: \d+
  defaults: { _controller: AppBundle:Cart:add }

shopping_cart_show:
  path: /shopping_cart
  defaults: { _controller: AppBundle:Cart:show }

shopping_cart_send_success:
  path: /shopping_cart_send_success
  defaults: { _controller: AppBundle:Cart:sendSuccess }