app:
    resource: '@AppBundle/Controller/'
    type: annotation

logout:
    path:   /logout

tamplarie_pvc:
  path: /tamplarie_pvc
  defaults: { _controller: AppBundle:Product:tamplariepvc }

cerere_oferta:
  path: /cerere_oferta
  defaults: { _controller: AppBundle:Oferta:cerere }

cerere_oferta_success:
  path: /cerere_oferta_success
  defaults: { _controller: AppBundle:Oferta:success }