AppBundle\Entity\Comanda:
  type: entity
  table: comanda
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  manyToOne:
    user:
      targetEntity: User
      joinColumn:
        name: user_id
        referencedColumnName: id