AppBundle\Entity\Contact:
  type: entity
  table: contact
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    first_name:
      type: string
      length: 255
    last_name:
      type: string
      length: 255
    email:
      type: string
      length: 255
    subject:
      type: text